### ISSUE TITLE
Running with podman does not work

### ISSUE THREAD

**Issue by PhilippRue** [PhilippRue/aiida-discover-section-minimal#1]
The app runs fine with `docker-compose` on my macbook and gives this output:

https://github.com/PhilippRue/aiida-discover-section-minimal/blob/master/example_output.png

Running on CentOS8 with `podman-compose` however does not work.

* I can build the image (`podman-compose build` succeeds including import of the test data into the database via `verdi import`).
* When running the app (`podman-compose up`) no data can be loaded:
```
2020-03-20 09:00:20,503 Error running application handler <bokeh.application.handlers.directory.DirectoryHandler object at 0x152451e38e50>: could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

File "__init__.py", line 126, in connect:
conn = _connect(dsn, connection_factory=connection_factory, **kwasync) Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bokeh/application/handlers/code_runner.py", line 179, in run
    exec(self._code, module.__dict__)
  File "/app/test-app/main.py", line 10, in <module>
    calc = load_node('3058bd6c-de0b-400e-aff5-2331a5f5d566')
  File "/usr/local/lib/python3.7/site-packages/aiida/orm/utils/__init__.py", line 204, in load_node
    query_with_dashes=query_with_dashes
  File "/usr/local/lib/python3.7/site-packages/aiida/orm/utils/__init__.py", line 78, in load_entity
    identifier, identifier_type, sub_classes=sub_classes, query_with_dashes=query_with_dashes
  File "/usr/local/lib/python3.7/site-packages/aiida/orm/utils/loaders.py", line 205, in load_entity
    builder, query_parameters = cls.get_query_builder(identifier, identifier_type, sub_classes, query_with_dashes)
  File "/usr/local/lib/python3.7/site-packages/aiida/orm/utils/loaders.py", line 166, in get_query_builder
    builder = cls._get_query_builder_uuid_identifier(identifier, classes, query_with_dashes)
  File "/usr/local/lib/python3.7/site-packages/aiida/orm/utils/loaders.py", line 128, in _get_query_builder_uuid_identifier
    builder = QueryBuilder()
  File "/usr/local/lib/python3.7/site-packages/aiida/orm/querybuilder.py", line 317, in __init__
    backend = backend or get_manager().get_backend()
  File "/usr/local/lib/python3.7/site-packages/aiida/manage/manager.py", line 129, in get_backend
    self._load_backend()
  File "/usr/local/lib/python3.7/site-packages/aiida/manage/manager.py", line 80, in _load_backend
    manager.load_backend_environment(profile, validate_schema=schema_check)
  File "/usr/local/lib/python3.7/site-packages/aiida/backends/manager.py", line 118, in load_backend_environment
    self.validate_schema(profile)
  File "/usr/local/lib/python3.7/site-packages/aiida/backends/manager.py", line 226, in validate_schema
    self.validate_schema_generation(profile)
  File "/usr/local/lib/python3.7/site-packages/aiida/backends/manager.py", line 285, in validate_schema_generation
    schema_generation_database = self.get_schema_generation_database()
  File "/usr/local/lib/python3.7/site-packages/aiida/backends/djsite/manager.py", line 81, in get_schema_generation_database
    result = backend.execute_raw(r"""SELECT tval FROM db_dbsetting WHERE key = 'schema_generation';""")
  File "/usr/local/lib/python3.7/site-packages/aiida/orm/implementation/django/backend.py", line 127, in execute_raw
    with self.cursor() as cursor:
  File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/aiida/orm/implementation/django/backend.py", line 117, in cursor
    yield self.get_connection().cursor()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
```

**Comment by PhilippRue** [comment]
Adding `network_mode: "host"` to the `docker-compose.yml` fixes this for `podman-compose` but then the `docker-compose` run does not run.

**Comment by PhilippRue** [comment]
> Adding `network_mode: "host"` to the `docker-compose.yml` fixes this for `podman-compose` but then the `docker-compose` run does not run.

Now (with commit 55815925ccbf9a4a91a432de75c6ae23f01d8a5f) two version of the docker-compose and Dockerfiles for docker and podman are included which fix this issue.

Therefore I close this issue now
